import { ShopItem } from '@/types/shop';

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'item_001',
    name: '启蒙书卷',
    description: '提升幼年成员资质，有概率提升一档',
    category: 'cultivate',
    priceType: 'silver',
    price: 500,
    effectType: 'upgrade_aptitude',
    effectValue: 0.3,
    limitType: 'daily',
    limitCount: 3,
    sortOrder: 1,
  },
  {
    id: 'item_002',
    name: '破境丹',
    description: '提升任一成年成员资质，概率触发突破',
    category: 'cultivate',
    priceType: 'silver',
    price: 1200,
    effectType: 'breakthrough',
    effectValue: 0.2,
    limitType: 'daily',
    limitCount: 1,
    sortOrder: 2,
  },
  {
    id: 'item_003',
    name: '延年益寿丹',
    description: '延长一位成员寿命上限24个月',
    category: 'prop',
    priceType: 'luckyCharm',
    price: 50,
    effectType: 'extend_life',
    effectValue: 24,
    limitType: 'weekly',
    limitCount: 2,
    sortOrder: 3,
  },
  {
    id: 'item_004',
    name: '转运符',
    description: '重新随机一位成员的资质（不可逆）',
    category: 'prop',
    priceType: 'luckyCharm',
    price: 80,
    effectType: 'reroll_aptitude',
    effectValue: 1,
    limitType: 'weekly',
    limitCount: 1,
    sortOrder: 4,
  },
  {
    id: 'item_005',
    name: '金饭碗',
    description: '永久提升一位成年成员10%收益',
    category: 'prop',
    priceType: 'silver',
    price: 3000,
    effectType: 'income_boost',
    effectValue: 0.1,
    limitType: 'unlimited',
    limitCount: 0,
    sortOrder: 5,
  },
  {
    id: 'item_006',
    name: '龙凤呈祥令',
    description: '立即解除添丁冷却时间，无需等待',
    category: 'prop',
    priceType: 'luckyCharm',
    price: 30,
    effectType: 'reset_cooldown',
    effectValue: 1,
    limitType: 'daily',
    limitCount: 2,
    sortOrder: 6,
  },
  {
    id: 'item_007',
    name: '书香门第匾',
    description: '提升全体少年成员资质概率10%',
    category: 'cultivate',
    priceType: 'silver',
    price: 2000,
    effectType: 'family_aptitude_boost',
    effectValue: 0.1,
    limitType: 'unlimited',
    limitCount: 0,
    sortOrder: 7,
  },
  {
    id: 'item_008',
    name: '福缘锦囊',
    description: '随机获得银两/福缘符奖励',
    category: 'prop',
    priceType: 'silver',
    price: 300,
    effectType: 'random_reward',
    effectValue: 1,
    limitType: 'daily',
    limitCount: 5,
    sortOrder: 8,
  },
];
